version: 0.2
environment_variables:
  plaintext:
    S3_BUCKET: diab-pred-ui
    APP: diab-pred-ui
phases:
  install:
    runtime-versions:
      nodejs: 22.0.0
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@18
  pre_build:
    commands:
      - echo "Running pre build steps....."
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration=production
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist s3://${S3_BUCKET}