version: 0.2
environment_variables:
  plaintext:
    S3_BUCKET: diab-pred-ui
    CLOUDFRONT_ID: E28S9G9K6JLRYG
    APP: diab-pred-ui
phases:
  install:
    runtime-versions:
      nodejs: 22.0.0
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@18
  pre_build:
    commands:
      - echo "Running pre build steps....."
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration=production
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/${APP}/browser/ s3://${S3_BUCKET} --delete
      - echo Creating cloud front invalidation...
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"